//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPPAssignment.Member
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Label lblUsername;
        protected global::System.Web.UI.WebControls.Label lblQuizzesTaken;
        protected global::System.Web.UI.WebControls.Label lblAverageScore;
        protected global::System.Web.UI.WebControls.Label lblDiscussions;
        protected global::System.Web.UI.WebControls.Label lblDaysActive;
        protected global::System.Web.UI.WebControls.GridView gvRecentQuizzes;
        protected global::System.Web.UI.WebControls.GridView gvRecentPosts;
    }
}
