//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPPAssignment.Member
{
    public partial class Discussion
    {
        protected global::System.Web.UI.WebControls.Button btnNewTopic;
        protected global::System.Web.UI.WebControls.Panel pnlNewTopic;
        protected global::System.Web.UI.WebControls.TextBox txtTopicTitle;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTitle;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.TextBox txtTopicDescription;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDescription;
        protected global::System.Web.UI.WebControls.Button btnSubmitTopic;
        protected global::System.Web.UI.WebControls.Button btnCancelTopic;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Repeater rptTopics;
        protected global::System.Web.UI.WebControls.Panel pnlNoTopics;
        protected global::System.Web.UI.WebControls.Panel pnlUpload;
        protected global::System.Web.UI.WebControls.FileUpload fuDocument;
        protected global::System.Web.UI.WebControls.Button btnUploadDoc;
        protected global::System.Web.UI.WebControls.Repeater rptDocuments;
    }
}
