//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPPAssignment.Admin
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Label lblTotalUsers;
        protected global::System.Web.UI.WebControls.Label lblTotalQuizzes;
        protected global::System.Web.UI.WebControls.Label lblTotalPlanets;
        protected global::System.Web.UI.WebControls.Label lblTotalTopics;
        protected global::System.Web.UI.WebControls.GridView gvRecentUsers;
        protected global::System.Web.UI.WebControls.GridView gvQuizActivity;
    }
}
