//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPPAssignment
{
    public partial class PlanetDetails
    {
        protected global::System.Web.UI.WebControls.Panel pnlDetails;
        protected global::System.Web.UI.WebControls.Label lblName;
        protected global::System.Web.UI.WebControls.Label lblDescription;
        protected global::System.Web.UI.WebControls.Label lblDiameter;
        protected global::System.Web.UI.WebControls.Label lblMass;
        protected global::System.Web.UI.WebControls.Label lblRotation;
        protected global::System.Web.UI.WebControls.Label lblMoons;
        protected global::System.Web.UI.WebControls.Label lblDistance;
        protected global::System.Web.UI.WebControls.Label lblOrbital;
        protected global::System.Web.UI.WebControls.Label lblFacts;
        protected global::System.Web.UI.WebControls.Panel pnlError;
    }
}
